name: Compile and upload code as an artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up artifacts and compress source code
        run: zip -r source.zip ./ ; mkdir downloads ; mv source.zip downloads/source.zip
      
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      
      - name: Build program using Platformio CLI
        run: pio run ; cp ./.pio/build/ATmega2560/firmware.hex downloads/firmware.hex

      - name: Upload source code and firmware as Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads